name = "extensionto-cms"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB_1"
database_name = "cms-db-1"
database_id = "a8f5-4a7b-8e3c-2e6d1b0f9c7d"
preview_database_id = "local-db-1"

[[d1_databases]]
binding = "DB_2"
database_name = "cms-db-2"
database_id = "b9f6-5b8c-9f4d-3f7e2c1a0d8e"
preview_database_id = "local-db-2"

[[d1_databases]]
binding = "DB_3"
database_name = "cms-db-3"
database_id = "c0g7-6c9d-0g5e-4g8f3d2b1e9f"
preview_database_id = "local-db-3"

[vars]
