name = "extensionto-cms"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB_1"
database_name = "shard_1"
database_id = "3581ec4b-c507-47ff-9d6e-23fbef1bbc99"
preview_database_id = "local-db-1"

[[d1_databases]]
binding = "DB_2"
database_name = "shard_2"
database_id = "7beb72e1-059f-42a6-b2df-e3d8d005efc3"
preview_database_id = "local-db-2"

[[d1_databases]]
binding = "DB_3"
database_name = "shard_3"
database_id = "7548d073-ef12-4afd-a597-96111a8c3f84"
preview_database_id = "local-db-3"

[vars]
