name = "backend"
main = "src/index.ts"
compatibility_date = "2024-05-29"

[[d1_databases]]
binding = "DB_1"
database_name = "DB_1"
database_id = "3c7dee75-4c33-413d-8576-607cbc22b5e6"

[[d1_databases]]
binding = "DB_2"
database_name = "DB_2"
database_id = "192da546-d1c6-432a-8540-ce5dea44566b"

[[d1_databases]]
binding = "DB_3"
database_name = "DB_3"
database_id = "a846d35d-4ee7-467b-ac98-ae18314df384"

[vars]
BEARER_TOKEN = "0600231590mM@"
USER_PASSWORD = "0600231590mM@"
