name = "extensionto-backend"
main = "src/index.ts"
compatibility_date = "2025-01-08"

[[d1_databases]]
binding = "DB_ACTIVE"
database_name = "shard_1"
database_id = "3581ec4b-c507-47ff-9d6e-23fbef1bbc99"

[[d1_databases]]
binding = "DB_REVIEW"
database_name = "shard_2"
database_id = "7beb72e1-059f-42a6-b2df-e3d8d005efc3"

[[d1_databases]]
binding = "DB_ARCHIVE"
database_name = "shard_3"
database_id = "7548d073-ef12-4afd-a597-96111a8c3f84"

[[r2_buckets]]
binding = "ARTICLES_BUCKET"
bucket_name = "extensionto-articles"

[env.production]
routes = [
  { pattern = "api.extensionto.com/*", zone_name = "extensionto.com" }
]